#!/usr/bin/env python3
"""Prove the hall maze is walkable, using the game's own distance field.

    python3 tools/mazecheck.py [seed-count]

The hall past gate two is a seven-metre grid of pillars with a wall across
every row and one doorway in it. A seed whose doorways happen to line up
behind a pillar seals a row, and one sealed row seals the rest of the game --
so this has to be re-run whenever the field changes.

Earlier this check lived in a JavaScript transcription of the C. That is the
kind of mirror that goes stale silently and then reassures you about code you
are no longer running. This one slices the field functions straight out of
src/game.c, compiles them with the host cc, and floods the real thing:

    cave_sdf(x, y, z) >= PLAYER_R  =  a place the player's sphere fits

The slice is delimited by the two markers below, so moving the field around
the file is fine; renaming or splitting cave_sdf is what would need attention.
"""
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAME = ROOT / "src" / "game.c"

SLICE_FROM = re.compile(r"^static\s+float\s+g_seed\s*;")
SLICE_TO = re.compile(r"^static\s+int\s+cave_ray\s*\(")

HARNESS = r"""
/* generated by tools/mazecheck.py -- do not edit */
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#define GATE_1 120.0f
#define GATE_2 240.0f
#define GATE_3 360.0f
#define GATE_END 480.0f
#define WAKE_Z (GATE_END + 46.0f)
#define GATE_R 9.5f
#define GATE_W 5.0f
#define DEPTH_FULL 480.0f
#define BRANCHES 26
#define BRANCH_SPACING 26.0f
#define BRANCH_LEN 17.0f
#define PLAYER_R 0.62f

/* surface_mix() reads the smoothed shock count: a crossed gate pulls the
 * backrooms look in early, which moves rock. Both ends of its range get
 * flooded, because the player can be anywhere in it when they walk the hall. */
static float g_shockf;

%(slice)s

/* --- the flood ---------------------------------------------------------- */

#define CELL   0.25f            /* finer than the 0.17 m walls are thick */
#define XSPAN  48.0f            /* the tunnel wanders ~5 m, gaps reach ~8 more */
#define ZLO    (GATE_2 + 10.0f) /* below the blend-in, safely inside the hall */
#define ZHI    WAKE_Z

static int NX, NZ;
static unsigned char *pass;
static int *queue;

static int idx(int ix, int iz) { return iz * NX + ix; }

/* The hall's y term is a slab centred on the tunnel; every wall and pillar is
 * y-independent. So the most open y at a given z is the slab's centre, and a
 * 2-D flood there is not an approximation of the 3-D one, it is its ceiling. */
static int walkable(int ix, int iz)
{
    float cx, cy;
    float x = -XSPAN + ix * CELL;
    float z = -(ZLO + iz * CELL);
    tunnel_centre(z, &cx, &cy);
    return cave_sdf(x, cy - 0.3f, z) >= PLAYER_R;
}

/* The hall stops at a wall with the door in it, so the last half-metre of the
 * grid is solid on purpose. "Reached the door" therefore means what the game
 * means by it in game.c: standing close enough that a ping opens it. */
#define DOOR_IZ ((int)((WAKE_Z - 1.6f - ZLO) / CELL))

/* Returns 1 if the door is reachable from the hall entrance. */
static int flood(int *reached_out, int *open_out, int *deepest_out)
{
    int ix, iz, head = 0, tail = 0, got_door = 0;
    int open = 0, reached = 0, deepest = 0;

    memset(pass, 0, (size_t)NX * NZ);

    for (iz = 0; iz < NZ; iz++)
        for (ix = 0; ix < NX; ix++)
            if (walkable(ix, iz)) { pass[idx(ix, iz)] = 1; open++; }

    /* seed from every open cell on the first row inside the hall */
    for (ix = 0; ix < NX; ix++)
        if (pass[idx(ix, 0)] == 1) { pass[idx(ix, 0)] = 2; queue[tail++] = idx(ix, 0); }

    while (head < tail) {
        int cur = queue[head++], cix = cur %% NX, ciz = cur / NX;
        static const int dx[4] = {1, -1, 0, 0};
        static const int dz[4] = {0, 0, 1, -1};
        int d;
        reached++;
        if (ciz > deepest) deepest = ciz;
        if (ciz >= DOOR_IZ) got_door = 1;
        for (d = 0; d < 4; d++) {
            int nx = cix + dx[d], nz = ciz + dz[d];
            if (nx < 0 || nx >= NX || nz < 0 || nz >= NZ) continue;
            if (pass[idx(nx, nz)] != 1) continue;
            pass[idx(nx, nz)] = 2;
            queue[tail++] = idx(nx, nz);
        }
    }
    *reached_out = reached;
    *open_out = open;
    *deepest_out = deepest;
    return got_door;
}

int main(int argc, char **argv)
{
    int trials = argc > 1 ? atoi(argv[1]) : 40;
    int t, blocked = 0;
    double worst_iso = 0.0;
    int worst_seed = -1;

    NX = (int)(2.0f * XSPAN / CELL) + 1;
    NZ = (int)((ZHI - ZLO) / CELL) + 1;
    pass  = malloc((size_t)NX * NZ);
    queue = malloc(sizeof(int) * (size_t)NX * NZ);
    if (!pass || !queue) { fprintf(stderr, "out of memory\n"); return 2; }

    printf("grid %%d x %%d at %%.2f m, hall z -%%.0f .. -%%.0f, clearance %%.2f m\n",
           NX, NZ, CELL, (double)ZLO, (double)ZHI, (double)PLAYER_R);

    for (t = 0; t < trials; t++) {
        static const float shocks[2] = {0.0f, 2.0f};
        int s;

        for (s = 0; s < 2; s++) {
            int reached, open, deepest, ok;
            double iso;

            /* the same rolls new_cave() makes, in the same order */
            g_rng    = (unsigned)(t * 2654435761u + 12345u);
            g_seed   = rndf() * 1000.0f;
            g_wander = 0.80f + rndf() * 0.45f;
            g_rough  = 0.70f + rndf() * 0.70f;
            g_shockf = shocks[s];
            build_branches();

            ok  = flood(&reached, &open, &deepest);
            iso = open ? 100.0 * (open - reached) / open : 0.0;
            if (iso > worst_iso) { worst_iso = iso; worst_seed = t; }
            if (!ok) {
                blocked++;
                printf("  BLOCKED  trial %%d shockf %%.1f  seed %%.3f wander %%.3f rough %%.3f"
                       "  -- flood died at z -%%.1f, door at -%%.1f\n",
                       t, (double)g_shockf, (double)g_seed,
                       (double)g_wander, (double)g_rough,
                       (double)(ZLO + deepest * CELL), (double)(WAKE_Z - 1.6f));
            }
        }
    }

    printf("%%d/%%d floods reach the door; worst isolated pocket %%.2f%%%% (trial %%d)\n",
           trials * 2 - blocked, trials * 2, worst_iso, worst_seed);
    return blocked ? 1 : 0;
}
"""


def slice_field(text):
    lines = text.splitlines()
    start = end = None
    for i, line in enumerate(lines):
        if start is None and SLICE_FROM.match(line):
            start = i
        elif start is not None and SLICE_TO.match(line):
            end = i
            break
    if start is None or end is None:
        raise SystemExit("could not find the field functions in src/game.c")
    return "\n".join(lines[start:end])


def main(argv):
    trials = argv[0] if argv else "40"
    src = HARNESS % {"slice": slice_field(GAME.read_text(encoding="utf-8"))}

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        (tmp / "mazecheck.c").write_text(src, encoding="utf-8")
        build = subprocess.run(
            ["cc", "-O2", "-std=c99", "-w", str(tmp / "mazecheck.c"),
             "-o", str(tmp / "mazecheck"), "-lm"],
            capture_output=True, text=True)
        if build.returncode:
            sys.stderr.write(build.stderr)
            return 2
        return subprocess.run([str(tmp / "mazecheck"), trials]).returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
