#!/usr/bin/env python3
"""Prove the hall maze is walkable, using the game's own distance field.

    python3 tools/mazecheck.py [seed-count]
    python3 tools/mazecheck.py -s 20260904 [more seeds...]
    python3 tools/mazecheck.py -f 997.999 1.214 0.914
    python3 tools/mazecheck.py -y -0.7 [any of the above]
    python3 tools/mazecheck.py -r 4 [any of the above]   # quarter-cell sampling

The first form samples the space of caves. The second floods the cave one
exact seed builds. The third floods a cave by the three numbers that actually
define it -- copy them out of the "cave seed .. wander .. rough" line a -shot
run writes to shotlog.txt, which is the only way to check the cave a capture
really walked: game_init's seed does not survive the click that starts a run.

-y sets how far below the tunnel centre to flood. The default -0.3 is the most
open slice there is, so it is a ceiling on walkability rather than a promise --
and the ceiling is not tight: a scripted walk measured the player floating
around 0.7 m below centre, where the same cells lose about 0.4 m of clearance.
Nothing gives the player a fixed height, so the honest check is a range.

The hall past gate two is a seven-metre grid of pillars with a wall across
every row and one doorway in it. A seed whose doorways happen to line up
behind a pillar seals a row, and one sealed row seals the rest of the game --
so this has to be re-run whenever the field changes.

Earlier this check lived in a JavaScript transcription of the C. That is the
kind of mirror that goes stale silently and then reassures you about code you
are no longer running. This one slices the field functions straight out of
src/game.c, compiles them with the host cc, and floods the real thing:

    cave_sdf(x, y, z) >= PLAYER_R  =  a place the player's sphere fits

The slice is delimited by the two markers below, so moving the field around
the file is fine; renaming or splitting cave_sdf is what would need attention.
"""
import pathlib
import re
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAME = ROOT / "src" / "game.c"

SLICE_FROM = re.compile(r"^static\s+float\s+g_seed\s*;")
SLICE_TO = re.compile(r"^static\s+int\s+cave_ray\s*\(")

HARNESS = r"""
/* generated by tools/mazecheck.py -- do not edit */
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#define GATE_1 120.0f
#define GATE_2 240.0f
#define GATE_3 360.0f
#define GATE_END 480.0f
#define WAKE_Z (GATE_END + 46.0f)
#define GATE_R 9.5f
#define GATE_W 5.0f
#define DEPTH_FULL 480.0f
#define PLAYER_R 0.62f
/* The last twenty metres are one straight corridor to the door, and past the
 * door is the room with the bulb. Both are outside the slice, like the gates. */
#define CORR_Z (WAKE_Z - 20.0f)
#define LAMP_Z (WAKE_Z + 26.0f)
/* BRANCHES and the BRANCH_* sizes are not repeated here: they live inside the
 * slice, and a second copy that disagreed would quietly flood a cave the game
 * does not have. Everything above this line is outside the slice. */

/* surface_mix() reads the smoothed shock count: a crossed gate pulls the
 * backrooms look in early, which moves rock. Both ends of its range get
 * flooded, because the player can be anywhere in it when they walk the hall. */
static float g_shockf;

/* The building does not undulate: one height and one corridor line are taken
 * at the entrance and held. new_attempt() sets these, and the flood has to set
 * them the same way -- left at zero the check floods a hospital built at y = 0
 * and a corridor down x = 0, which is not the building the game has, and would
 * have reported on a maze nobody plays. */
static float g_hosp_y;
static float g_corr_x;
/* Shut. That the door opens once you are in front of it is not in question;
 * whether you can get in front of it is the whole point of this tool. */
static float g_door_open;

%(slice)s

/* --- the flood ---------------------------------------------------------- */

#define CELL   0.25f            /* finer than the 0.17 m walls are thick */
#define XSPAN  48.0f            /* the tunnel wanders ~5 m, gaps reach ~8 more */
/* The flood used to step one cell at a time, which is fine for a maze whose
 * features are cells -- and blind to anything narrower. The transition into
 * the building opens along a corridor 5.2 m wide on a wandering axis, and a
 * 7 m lattice loses the thread of it between rows and calls the game sealed.
 * STEP is the sampling pitch; the cell size is still CELL. */
static float g_step = CELL;
/* At the doorway, not ten metres past it. The hall used to be pillars, so any
 * row was as good a place to start as any other; the building is rooms with
 * one doorway apiece, and a grid starting inside it seeds the flood in a room
 * whose only way out faces back the way you came -- outside the grid. Every
 * seed came back sealed, from a maze that is not. */
#define ZLO    (GATE_2 + 4.0f)
#define ZHI    WAKE_Z

static int NX, NZ;
static unsigned char *pass;
static int *queue;

static int idx(int ix, int iz) { return iz * NX + ix; }

/* The hall's walls and pillars are y-independent, but the slab it is all cut
 * out of is not: drop half a metre and the same corridor loses about that much
 * clearance. So a flood at one height is a slice, and the slice nearest the
 * centre is the most generous one there is -- a ceiling on walkability, not a
 * promise. Which is why -y exists. */
static float g_probe_y = -0.3f;   /* metres below the tunnel centre */

/* Probed against the height the building is actually at, not the tunnel's.
 * The hall used to inherit the cave's wandering axis, so following the tunnel
 * centre was the same thing as following the floor. It is not any more: the
 * undulation dies out over the first fifteen metres and the floor then holds
 * one height, which can be metres from where the axis has drifted to. Probing
 * the old way put the sample inside rock at the very first row -- the flood
 * had nowhere to start and reported the game unfinishable on every seed. */
static int walkable(int ix, int iz)
{
    float cx, cy, st2, cyh;
    float x = -XSPAN + ix * g_step;
    float z = -(ZLO + iz * g_step);
    tunnel_centre(z, &cx, &cy);
    st2 = smoothstep01(GATE_2 + 4.0f, GATE_2 + 19.0f, -z);
    cyh = cy * (1.0f - st2) + g_hosp_y * st2;
    return cave_sdf(x, cyh + g_probe_y, z) >= PLAYER_R;
}

/* The hall stops at a wall with the door in it, so the last half-metre of the
 * grid is solid on purpose. "Reached the door" therefore means what the game
 * means by it in game.c: standing close enough that a ping opens it. */
#define DOOR_IZ ((int)((WAKE_Z - 1.6f - ZLO) / g_step))

/* Returns 1 if the door is reachable from the hall entrance. */
static int flood(int *reached_out, int *open_out, int *deepest_out)
{
    int ix, iz, head = 0, tail = 0, got_door = 0;
    int open = 0, reached = 0, deepest = 0;

    memset(pass, 0, (size_t)NX * NZ);

    for (iz = 0; iz < NZ; iz++)
        for (ix = 0; ix < NX; ix++)
            if (walkable(ix, iz)) { pass[idx(ix, iz)] = 1; open++; }

    /* seed from every open cell on the first row inside the hall */
    for (ix = 0; ix < NX; ix++)
        if (pass[idx(ix, 0)] == 1) { pass[idx(ix, 0)] = 2; queue[tail++] = idx(ix, 0); }

    while (head < tail) {
        int cur = queue[head++], cix = cur %% NX, ciz = cur / NX;
        static const int dx[4] = {1, -1, 0, 0};
        static const int dz[4] = {0, 0, 1, -1};
        int d;
        reached++;
        if (ciz > deepest) deepest = ciz;
        if (ciz >= DOOR_IZ) got_door = 1;
        for (d = 0; d < 4; d++) {
            int nx = cix + dx[d], nz = ciz + dz[d];
            if (nx < 0 || nx >= NX || nz < 0 || nz >= NZ) continue;
            if (pass[idx(nx, nz)] != 1) continue;
            pass[idx(nx, nz)] = 2;
            queue[tail++] = idx(nx, nz);
        }
    }
    *reached_out = reached;
    *open_out = open;
    *deepest_out = deepest;
    return got_door;
}

int main(int argc, char **argv)
{
    int a = 1;
    int exact, field, trials;
    if (argc > 2 && strcmp(argv[1], "-y") == 0) { g_probe_y = (float)atof(argv[2]); a = 3; }
    if (argc > a + 1 && strcmp(argv[a], "-r") == 0) { g_step = CELL / (float)atoi(argv[a+1]); a += 2; }
    exact = argc > a && strcmp(argv[a], "-s") == 0;
    field = argc > a + 3 && strcmp(argv[a], "-f") == 0;
    trials = field ? 1 : exact ? argc - a - 1 : (argc > a ? atoi(argv[a]) : 40);
    int t, blocked = 0;
    double worst_iso = 0.0;
    int worst_seed = -1;

    NX = (int)(2.0f * XSPAN / g_step) + 1;
    NZ = (int)((ZHI - ZLO) / g_step) + 1;
    pass  = malloc((size_t)NX * NZ);
    queue = malloc(sizeof(int) * (size_t)NX * NZ);
    if (!pass || !queue) { fprintf(stderr, "out of memory\n"); return 2; }

    printf("grid %%d x %%d at %%.2f m, hall z -%%.0f .. -%%.0f, clearance %%.2f m,"
           " probing %%.2f m below centre\n",
           NX, NZ, g_step, (double)ZLO, (double)ZHI, (double)PLAYER_R, (double)g_probe_y);

    for (t = 0; t < trials; t++) {
        static const float shocks[2] = {0.0f, 2.0f};
        int s;

        for (s = 0; s < 2; s++) {
            int reached, open, deepest, ok;
            double iso;

            /* the same rolls new_attempt() makes, in the same order */
            if (field) {
                g_seed   = (float)atof(argv[a + 1]);
                g_wander = (float)atof(argv[a + 2]);
                g_rough  = (float)atof(argv[a + 3]);
            } else {
                g_rng    = exact ? (unsigned)strtoul(argv[a + 1 + t], 0, 10)
                                 : (unsigned)(t * 2654435761u + 12345u);
                if (!g_rng) g_rng = 1u;
                g_seed   = rndf() * 1000.0f;
                g_wander = 0.80f + rndf() * 0.45f;
                g_rough  = 0.70f + rndf() * 0.70f;
            }
            g_shockf = shocks[s];
            build_branches();
            {   /* the same two the game takes in new_attempt(), in the same
                   order, off the cave that was just rolled */
                float hx, hy, qx, qy;
                tunnel_centre(-(GATE_2 + 4.0f), &hx, &hy);
                g_hosp_y = hy;
                tunnel_centre(-CORR_Z, &qx, &qy);
                g_corr_x = qx;
                g_door_open = 0.0f;
            }

            ok  = flood(&reached, &open, &deepest);
            iso = open ? 100.0 * (open - reached) / open : 0.0;
            if (iso > worst_iso) { worst_iso = iso; worst_seed = t; }
            if (!ok) {
                blocked++;
                printf("  BLOCKED  %%s%%s shockf %%.1f  seed %%.3f wander %%.3f rough %%.3f"
                       "  -- flood died at z -%%.1f, door at -%%.1f\n",
                       field ? "field" : exact ? "seed " : "trial ",
                       field ? "" : exact ? argv[a + 1 + t] : "",
                       (double)g_shockf, (double)g_seed,
                       (double)g_wander, (double)g_rough,
                       (double)(ZLO + deepest * CELL), (double)(WAKE_Z - 1.6f));
            }
        }
    }

    printf("%%d/%%d floods reach the door; worst isolated pocket %%.2f%%%% (trial %%d)\n",
           trials * 2 - blocked, trials * 2, worst_iso, worst_seed);
    return blocked ? 1 : 0;
}
"""


def slice_field(text):
    lines = text.splitlines()
    start = end = None
    for i, line in enumerate(lines):
        if start is None and SLICE_FROM.match(line):
            start = i
        elif start is not None and SLICE_TO.match(line):
            end = i
            break
    if start is None or end is None:
        raise SystemExit("could not find the field functions in src/game.c")
    return "\n".join(lines[start:end])


def main(argv):
    args = argv if argv else ["40"]
    src = HARNESS % {"slice": slice_field(GAME.read_text(encoding="utf-8"))}

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        (tmp / "mazecheck.c").write_text(src, encoding="utf-8")
        # "cc" is not a name Windows has, and an executable there needs the
        # extension, so the host compiler is looked up rather than assumed.
        exe = tmp / ("mazecheck.exe" if os.name == "nt" else "mazecheck")
        names = [os.environ["CC"]] if os.environ.get("CC") else []
        names += ["cc", "gcc", "clang", "x86_64-w64-mingw32-gcc"]
        build = None
        for name in names:
            found = shutil.which(name)
            if not found:
                continue
            build = subprocess.run(
                [found, "-O2", "-std=c99", "-w", str(tmp / "mazecheck.c"),
                 "-o", str(exe), "-lm"],
                capture_output=True, text=True)
            if build.returncode == 0:
                break
        if build is None:
            sys.stderr.write("no C compiler found (tried %s)\n" % ", ".join(names))
            return 2
        if build.returncode:
            sys.stderr.write(build.stderr)
            return 2
        return subprocess.run([str(exe)] + args).returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
